name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        php_extensions: gd
        version: 9.6.11

    # Étape pour exécuter l'action "Code Coverage Summary"
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: src/coverage.cobertura.xml
        badge: true 
        fail_below_min: true  
        format: markdown 
        hide_branch_rate: false  
        hide_complexity: false 
        indicators: true 
        output: both  
        thresholds: '50 75' 
      
    # ... then your own project steps ...

          
    