name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        php_extensions: gd xdebug mbstring
        version: 9.6.11
        coverage_cobertura: coverage.cobertura.xml
      env:
        XDEBUG_MODE: coverage

    # Étape pour executer l'action Code Coverage Summary
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        badge: true 
        fail_below_min: true  
        format: markdown 
        hide_branch_rate: false  
        hide_complexity: false 
        indicators: true 
        output: both  
        thresholds: '50 75' 


    # Etape pour executer l'action PHP Code Sniffer
    - name: PHP Code Sniffer (php-actions)
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.1
        path: lib/
        standard: PSR1
            
      
    # ... then your own project steps ...

          
    